config/routes.rb
Rails.application.routes.draw do



  get '/project' => 'pages#project'

  get '/stage' => 'pages#stage'

  get '/about' => 'pages#about'

  get '/reviews/download' => 'reviews#download'

  resources :reviews, shallow: true do
    resources :replies
  end

  resources :pages, :only => :index

  root 'pages#index'
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def philosophy
  end

  def project
  end

  def stage
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @review = Review.find_by(id: params[:review_id])
    @reply = Reply.new
  end

  def create
    Reply.create(create_params)
    redirect_to :reviews, notice: '投稿が完了しました'
  end

  private
  def create_params
    params.require(:reply).permit(:comment, :nickname).merge(
        review_id: params[:review_id]
      )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def download
    file_name = "script.pdf"
    filepath = Rails.root.join('public',file_name)
    send_file(filepath, :filename => file_name, :type => "application/pdf", :disposition => 'attachment')
  end

  def create
    Review.create(create_params)
    redirect_to reviews_url, notice: '投稿が完了しました'
  end

  private
  def create_params
    params.require(:review).permit(:comment, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>現代サムシング研究所</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta  name="viewport" content="width=device-width, user-scalable=yes, width=860">
</head>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91260326-1', 'auto');
  ga('send', 'pageview');

</script>


<body id="page-top">

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="/">現代サムシング研究所</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="/about" data-turbolinks="false">現代サムシング研究所とは</a>
                </li>
                <li>
                    <a class="page-scroll" href="/stage">公演情報</a>
                </li>
                <li>
                    <a class="page-scroll" href="/project">クラウドファンディング</a>
                </li>
                <!-- <li>
                    <a class="page-scroll" href="/reviews">２月公演の脚本をみる</a>
                </li> -->
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<%= yield %>

<footer style="width: 100%; height: 70px; margin-bottom: 0px; background-color: #5E6060;">
    <p style="color: white; top: 0; bottom: 0; margin: auto; font-family: "Hiragino Kaku Gothic Pro";>Copyright(C) 2016 Laboratory of modern something. All Rights Reserved.</p>
</footer>

<script src="https://use.typekit.net/lqg6jli.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
</body>
</html>

app/views/pages/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Contact</h2>
                <hr class="primary">
                <p style="font-size: calc(100.5% + 6 * (100vw - 320px) / 600);">ツイッターアカウント稼働中！<br>メールでのお問い合わせもお気軽にどうぞ！</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <img src="/images/407-twitter.png"><br>
                <a href="https://twitter.com/some_labo?lang=ja" style="font-size: 17px;">@some_labo</a><br><br>
            </div>
            <div class="col-lg-4 text-center">
                <img src="/images/388-mail.png"><br>
                <p><a href="mailto:your-email@your-domain.com">something.labo@gmail.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/pages/about.html.erb
<header id="blur">
    <div class="header-content">
        <div class="header-content-inner">
            <h1>about</h1>
            <hr>
            <p><b>現代サムシング研究所とは？</b></p>
        </div>
    </div>
</header>

<aside class="bg-dark" id="white">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>MISSION</h2>
            <p>ミッション</p><br>
            <h3><strong>創作活動の集合体として、<br>人、技術、心が<br>一つになる瞬間、空間を<br>作り上げる。</strong></h2>
        </div>
    </div>
</aside>

<section class="bg-primary" id="play-stone">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <p>音楽、ファッション、デザイン、<br>映像、写真、デジタルアート・・・<br><br>
                    創作活動には様々な<br>ジャンルがあります。<br><br>
                    それらを一つの場所に集め、<br>組み合わせることで、<br><br>
                    大きな熱量を生み出し、<br>大きな感動を呼ぶと、<br>私たちは信じています。<br><br>
                    バラバラのものを手軽に<br>「集め」、「組み合わせ」、<br>「実験する」場所を創り出すことが、<br>
                    私たちの存在意義だと考えています。
                </p>
            </div>
        </div>
    </div>
</section>


<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>How We Achieve?</h2>
        </div>
    </div>
</aside>

<section class="bg-primary" id="white">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h3 class="section-heading"><strong>クラウドファンディングで<br>仲間と資金を集めて<br>作品を作り上げる。</strong></h3>
            </div>
        </div>
    </div>
</section>

<section class="bg-primary" id="art">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <p>ビジョン達成のため、<br>クラウドファンディングを活用して<br>作品作りを行います。<br><br>
                主体は支援者。<br><br>
                支援者自身が、物語のテーマを<br>設計します。<br><br>
                役者・脚本・音響・映像・デザイン<br>衣装、写真、イラストなど<br><br>
                作品作りに欠かせない様々な要素を<br>
                支援者からかき集めて統合し、<br>
                一つの作品を共に創り上げます。<br><br>
                年齢、経歴、職種、役職等<br>異なる立場を持つ支援者が、<br>
                フラットでオープンな<br>関係性で交わることで、<br>
                誰も予想できない作品を目指します。<br><br></p>
            </div>
        </div>
    </div>
</section>

<section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">PROJECTS</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 text-center">
                    <div class="service-box">
                        <i><img src="images/205-flag.png"></i>
                        <h3>旗揚げ公演</h3>
                        <p class="text-muted">私たちは何者で、何を考えているのか、<br>皆様に直接届けるべく、<br>リアルイベントを実施。</p><br>
                        <a href="/stage" class="btn btn-primary btn-xl">詳細ページ</a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 text-center">
                    <div class="service-box">
                        <i><img src="images/166-rocket.png"></i>
                        <h3>クラウドファンディング</h3>
                        <p class="text-muted">MISSION達成に欠かせない、<br>「人」「資金」「技術」を<br>クラウドファンディング上で集めたい。</p><br>
                        <a href="/project" class="btn btn-primary btn-xl">詳細ページ</a>
                    </div>
                </div>
            </div>
        </div>
</section>

<!-- <aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>脚本、公開中！！</h2>
            <hr>
            <p class="text-faded">創作活動の民主化への、はじめの一歩として<br>旗揚げ公演の脚本を公開しています。<br><br>皆様からご意見を募り、<br>皆様と共に改善するためです。<br><br>ぜひ、我々の脚本をご覧ください。</p>
            <a href="/reviews" class="btn btn-primary btn-xl">脚本をみる</a>
        </div>
    </div>
</aside> -->

<aside class="bg-dark" id="member">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>メンバー紹介</h2>
            <p>（画像をクリック）</p>
        </div>
    </div>
</aside>

<!-- jQuery付きの方に不具合が出た際の保険 -->
<!-- <div class="row">
  <div class="col-sm-12 col-md-4">
    <div class="thumbnail">
      <img src="images/onot.jpg">
      <div class="caption">
        <h3>小野翼</h3>
        <p>現代サムシング研究所所長<br><br>サムシング研究の第一人者。 大相撲とチューイングガム「ガブリチュウ」が好きで知られる所長。好きな力士はもちろん稀勢の里。好きなガブリチュウはもちろんマスカット。どちらが好きかどうかがわかるのは、まだ後のことである。</p>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-4">
    <div class="thumbnail">
      <img src="images/otsu.jpg">
      <div class="caption">
        <h3>乙幡進悟</h3>
        <p>現代サムシング研究所副所長<br>役者・庶務<br><br>言わずと知れた小野翼の右腕。口を開けば、出てくる言葉は文句か批判。真顔はそこそこだが笑うと残念」という評価に、本人は「逆ではないか」と反論している。好きな寿司ネタはネギトロ。信じられないほど身体が硬い。</p>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-4">
    <div class="thumbnail">
      <img src="images/kitazoe.jpg">
      <div class="caption">
        <h3>北添真広</h3>
        <p>現代サムシング研究所副所長<br>WEBエンジニア<br><br>2016年11月にRUBYを勉強し始めた、ひよっ子エンジニア。根っからのサザンオールスターズ好き。好きな楽曲は「希望の轍」。休日は色々と出歩きたい派。最近購入したカメラで各地の写真を撮るのがマイブーム。愛用機はソニーのα7。</p>
      </div>
    </div>
  </div>
</div> -->

<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="javascript:void(0)" class="portfolio-box" id="ono-a">
                    <img src="images/onot.jpg" class="img-responsive" alt="" id="ono">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-name">
                                小野翼
                            </div>
                            <div class="project-category text-faded">現代サムシング研究所所長<br><br>サムシング研究の第一人者。<br>大相撲とソフトキャンディ「ガブリチュウ」好きで知られる所長。好きな力士はもちろん稀勢の里。好きなガブリチュウはもちろんマスカット味。そのどちらがより好きなのか。分かるのは後の話である。
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="javascript:void(0)" class="portfolio-box" id="otsu-a">
                    <img src="images/otsu.jpg" class="img-responsive" alt="" id="otsu">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-name">
                                乙幡進悟
                            </div>
                            <div class="project-category text-faded">現代サムシング研究所副所長<br>役者・庶務<br><br>言わずと知れた所長の右腕。<br>口を開けば、出てくる言葉は文句か批判。「真顔はそこそこだが笑うと残念」という評価に、本人は「逆ではないか」と反論している。好きな寿司ネタはネギトロ。信じられないほど身体が硬い。
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="javascript:void(0)" class="portfolio-box" id="kitazoe-a">
                    <img src="images/kitazoe.jpg" class="img-responsive" alt="" id="kitazoe">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-name">
                                北添真広
                            </div>
                            <div class="project-category text-faded">現代サムシング研究所副所長<br><br>幼少の頃からサザンオールスターズを聞いて育った、生粋のサザンファン。休日は色々と出歩きたい派で、各地の写真を撮るのがマイブーム。愛用機はソニーのα7。
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<%= render :partial => "contact" %>

app/views/pages/index.html.erb
<header class="top-header">
    <div class="header-section-title">
        <h1 style="margin: 2em 20px 0px 0px; line-height: 7rem;">
        <a href="#concept">ABOUT</a><br>
        <a href="#experiment">EXPERIMENT</a><br>
        <a href="#crowd">CROWD FUNDING</a></h1>
    </div>
    <div class="header-content">
        <div class="header-content-inner">
        </div>
    </div>
</header>

<div class="jumbotron" style="background-image: url(/images/main_04.png);" id="concept">
  <h1 class="section-title">ABOUT</h1>
  <h3 class="copy">現代サムシング研究所は、<br>2017年に始動した<strong>実験的創作活動集団</strong>である。</h3><br><br>
  <a href="/about"><img src="images/more_1.png" class="more"></a>
</div>

<div class="jumbotron" style="background-image: url(/images/main_06.png);" id="experiment">
  <h1 class="section-title">EXPERIMENT</h1>
  <h3 class="copy">
      <span style="font-size: 1.5rem;"><u><b>第零ノ実験</b></u></span><br><br>
      舞台<br><span style="font-size: 1.3rem;"><b>『帰還～超一流の幸福術～』</b><br></span>開催決定！<br></h3><br>
      <h3 style="line-height: 1.6em;" class="copy">主演 / <span style="font-size: 1.5rem;"><b>永井理子</b></span><br>女子高生ミスコン2015-2016グランプリ<br>テラスハウス出演
  </h3><br><br>
  <a href="/stage"><img src="images/more_1.png" class="more"></a>
</div>

<div class="jumbotron" style="background-image: url(/images/main_05.png);" id="crowd">
  <h1 class="section-title">CROWD FUNDING</h1>
  <h3 class="copy"><b>Coming Soon!!</b></h3><br><br>
  <a href="/project"><img src="images/more_1.png" class="more"></a>
</div>

<%= render :partial => "contact" %>

app/views/pages/project.html.erb
<header id="audience2">
    <div class="header-content">
        <div class="header-content-inner">
            <h1>project</h1>
            <hr>
            <p>現代サムシング研究所の<br>クラウドファンディング</p>
        </div>
    </div>
</header>

<!-- <section class="bg-primary" id="white">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading"><strong>制作過程全オープン！<br>支援者参加型のお芝居を<br>創り上げたい！！</strong></h2>
            </div>
        </div>
    </div>
</section>

<section class="bg-primary" id="crowd">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h3 class="section-heading">創作活動の集合体として、<br>人、技術、心が<br>一つになる瞬間、空間を<br>作り上げる。</h3>
                <hr>
                <p>このミッション達成に向けて<br>挑戦するプロジェクトです。<br><br>制作過程全オープン。<br><br>パトロンとなってくださった方は、<br>創作活動にご参加いただける<br>権利を得られます。<br><br>皆さんと作る舞台にふさわしい、<br>立派な劇場をご用意いたします。</p>
            </div>
        </div>
    </div>
</section> -->

<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Coming Soon...</h2>
            <p class="text-faded"><br>こちらのページとツイッター公式アカウントで<br>随時情報公開していく予定です！<br>ツイッターでフォローしてみてください！</p>
            <a href="https://twitter.com/some_labo?lang=ja" style="font-size: 17px;">@some_labo</a><br><br>
        </div>
    </div>
</aside>

<%= render :partial => "contact" %>

app/views/pages/stage.html.erb
<div id="main">

<div class="jumbotron" style="background-image: url(/images/stage_page_001.png); min-height: 950px;">
</div>

<div class="jumbotron" style="background-image: url(/images/stage_page_004.png); min-height: 950px;">
</div>

<div class="jumbotron" style="background-image: url(/images/stage_page_cast.png); min-height: 950px;">
</div>

<div class="jumbotron" style="background-image: url(/images/stage_page_006.png); min-height: 950px;">
</div>

<div class="jumbotron" style="background-image: url(/images/stage_page_007.png); min-height: 950px;"><br><br>
    <h1 class="section-title">TIMET<span class="title-colored">A</span>BLE</h1><br><br>
    <h2>2017/2/24[fri]〜26[sun]</h2><br><br>
    <h3 style="line-height: 2rem;">
        2/24[fri]...　　　　　15:00/19:00<br>
        2/25[sat]...&nbsp;　11:00/15:00/19:00<br>
        2/26[sun]...　11:00/14:30/18:00
    </h3>
    <br>
    <br>
    <br>
    <h1 class="section-title"><span class="title-colored">A</span>CCESS</h1><br>
    <h2>荻窪小劇場</h2><br><br>
    <a href="https://www.google.co.jp/maps/place/%E8%8D%BB%E7%AA%AA%E5%B0%8F%E5%8A%87%E5%A0%B4/@35.703297,139.6247402,17z/data=!3m1!4b1!4m5!3m4!1s0x6018f20a791ddf27:0x7299287de02c49cf!8m2!3d35.7032927!4d139.6269342"><img src="images/stage_page_009.png"></a>
</div>

<div class="jumbotron" style="background-image: url(/images/stage_page_007.png); min-height: 950px;"><br><br>
    <h1 class="section-title">T<span class="title-colored">I</span>CKET</h1><br><br>
    <h2>
        当日券　　　　　　　　...4500円<br>
        前売り券　　　　　　　...4000円<br>
        学生（当日・前売り）　...3500円
    </h2><br>
    <a href="https://ticket.corich.jp/apply/80248/" target="_blank">
        <h2 style="color: white;">ご予約はこちら</h2>
    </a><br><br>
    <h3>公演時間から選ぶ</h3>
                <iframe src="https://ticket.corich.jp/stage/bp/timetable.php?sid=80248&ad=26%2C24%2C5%2C17&view=10&body=&color=&td_bo=&td_co=&th_bo=&th_co=&t_bo=&t_co=&link=&border=" style="width: auto; min-height: 250px; border="0"; frameborder="no";"></iframe><br />
                [PR] <a href="https://ours-sr.co.jp/station" target="_blank" style="font-size: 6px">訪問看護ステーション</a>
                <a href="http://fxsystrehikaku.com" target="_blank" style="font-size: 6px;">ミラートレーダー</a>
                <a href="http://fx.manepoke.jp" target="_blank" style="font-size: 6px;"">FX初心者</a>
                <a href="http://stage.corich.jp/bbs?category_id=6" target="_blank" style="font-size: 6px;">オーディション</a>
</div>

app/views/replies/new.html.erb
<h4 style="margin-top: 60px;"><b>返信先のコメント</b></h4>
<div class="panel panel-default">
  <div class="panel-heading">
    <i class="glyphicon glyphicon-user"></i><b><%= @review.nickname %></b>
  </div>
  <div class="panel-body">
    <%= @review.comment %>
  </div>
</div>
<br><br>

<h4><b>返信コメントを書く</b></h4>
<%= form_for [@review, @reply] do |f| %>
  <%= f.label :ニックネーム %>
  <br>
  <%= f.text_field :nickname, placeholder: "ニックネームを記入" %>
  <br>
  <%= f.label :コメント %>
  <br>
  <%= f.text_area :comment, placeholder: "コメントを記入", :size => '60x10' %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to '戻る', reviews_path %>

app/views/reviews/index.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>script</h1>
            <hr>
            <p>旗揚げ公演の脚本を公開中！<br>ご意見ご感想をコメントできます！</p>
            <a href="/reviews/download" class="btn btn-primary btn-xl" target="_blank">pdfで見る</a>
        </div>
    </div>
</header>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">コメント</h2>
                <hr class="light">
                <a href="/reviews/new" class="btn btn-default btn-xl">コメントを投稿する</a>
            </div>
        </div>
    </div>
</section>

<br>

<% @reviews.each do |review| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><i class="glyphicon glyphicon-user"></i><b><%= review.nickname %></b></h4>
    </div>
    <div class="panel-body">
      <%= simple_format(review.comment) %>
    </div>
  </div>
  <%= link_to 'このコメントに返信する', new_review_reply_path(review_id: review.id) %>
  <br><br>

  <% if review.replies.present? %>
  <h3>返信コメント</h3>
  <% end %>

    <% review.replies.each do |reply| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><i class="glyphicon glyphicon-user"></i><b><%= reply.nickname %></b></h4>
        </div>
        <div class="panel-body">
          <%= simple_format(reply.comment) %>
        </div>
      </div>
    <% end %>
  <br>
  <hr>
<% end %>

app/views/reviews/new.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">コメントを書く</h2>
                <hr class="light">
                <p class="text-faded">脚本についてのコメントをお聞かせください！<br>あなたの意見がそのまま反映されるかもしれません</p>
            </div>
        </div>
    </div>
</section>


<%= form_for @review do |f| %>
  <%= f.label :ニックネーム %>
  <br>
  <%= f.text_field :nickname, placeholder: "ニックネームを記入" %>
  <br>
  <%= f.label :コメント %>
  <br>
  <%= f.text_area :comment, placeholder: "コメントを記入", :size => "60x10" %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to '戻る', reviews_path %>